# Generated by Django 2.2 on 2021-06-07 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 8, 41, 31, 584283, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
